# Generated by Django 3.2.16 on 2023-01-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payup', '0002_alter_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordprod',
            name='scount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5),
            preserve_default=False,
        ),
    ]
