# Generated by Django 3.2.16 on 2023-01-15 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payup', '0003_ordprod_scount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordprod',
            name='scount',
        ),
    ]
