# Generated by Django 3.2.16 on 2023-02-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payup', '0004_remove_ordprod_scount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='owner',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
