# Generated by Django 3.2.16 on 2023-02-23 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
