# Generated by Django 3.2.16 on 2022-12-22 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='featured_image',
        ),
    ]
