# Generated by Django 3.2.16 on 2022-12-22 14:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_cat_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
