# Generated by Django 3.2.16 on 2022-12-22 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_cat_featured_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cat',
            options={'ordering': ['-created_on']},
        ),
    ]
