# Generated by Django 3.2.16 on 2022-12-22 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_cat_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cat',
        ),
    ]
