# Generated by Django 3.2.16 on 2023-01-24 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='article',
            new_name='producup',
        ),
    ]
