# Generated by Django 3.2.16 on 2023-01-24 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
